### ISSUE TITLE
Length of manuscript 

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#14]
The present state is approach 2x the suggested maximum length (250-1000 words).

Is this a concern?

**Comment by yarikoptic** [comment]
I think that we ~~could~~should squeeze it up a bit after we feel that it has all the pieces just to become more succinct but otherwise I wouldn't worry about it and leave to reviewers to flag but I don't think at 2x it would be a concern

**Comment by mih** [comment]
If length is no concern, there is no point in keeping this open.
