### ISSUE TITLE
Authorship: opt-in

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#2]
The rules are (from https://joss.readthedocs.io/en/latest/submitting.html#authorship):

> Purely financial (such as being named on an award) and organizational (such as general supervision of a research group) contributions are not considered sufficient for co-authorship of JOSS submissions, but active project direction and other forms of non-code contributions are. The authors themselves assume responsibility for deciding who should be credited with co-authorship, and co-authors must always agree to be listed. In addition, co-authors agree to be accountable for all aspects of the work, and to notify JOSS if any retraction or correction of mistakes are needed after publication.

If we agree on the scope of the paper being datalad-core #1 this makes 34 contributors to the code on its github repo obvious co-author candidates. I can only think of one person with "directional" influence that is not on this list. My proposal would be to approach them, asking whether they would want to participate in the drafting of the manuscript, and thereby become co-authors under the terms quoted above.

I particularly do not mind a long author list. And I do not see the need for a "minimum code contribution" or anything like that. All these people either are or were active contributors or early adopters that registered that fact with a contribution of some kind. I also do not mind extending that list -- I just thought it would be a good starting point.

edit by @yarikoptic : a list of contributors prepared / acted on in a separate repo (should have just kept everything here) -- https://github.com/datalad/datalad-git-bug-dumps (json files with emails are under annex and not shared ATM)

**Comment by yarikoptic** [comment]
Let's get a first working draft and invite all via email - github `@mentions` might be filtered out etc.

**Comment by yarikoptic** [comment]
based on git-bug import/ls, https://github.com/datalad/datalad-git-bug-dumps/commit/4338d11fda3d5950775e699c0e62f442218503cc lists everyone who ever filed (106) or participated (138) in an issue (sorted in decreasing order by number of opened issues). No effort was made to "de-duplicate" etc.  If we decide to go e.g. with everyone who filed an issue, it would add about 70 ppl.  

I would say we do make a cutoff. It could be very liberal if we include everyone who showed notable "consistency" in participation, thus cutting off at either filed or participated in `>=3` issues (1 - not consistent, 2 - not notable consistency, 3 - consistent enough ;)). The result of such ordering is https://github.com/datalad/datalad-git-bug-dumps/commit/3b880d3641181fdee1b7476d1944ee0db005616a#diff-e18dbddc358a1618e0c567e2a7b0c5d03b1f4e90b177b53fd14b2242438ea420R1  and then 43 potential candidates make the cut-off (not sure how many additional to the list of contributors from commits it would be, but probably under 10)

WDYT?

edit1: subsequent commit in that repo to the tool also fetches emails for the github users where available "publicly" (still need github auth token to fetch)

**Comment by vsoch** [comment]
I would like to participate!

**Comment by yarikoptic** [comment]
> I would like to participate!

Please add yourself (PR) as instructed in yet to be emailed letter (https://github.com/datalad/datalad-paper-joss/pull/20) . Paper draft is in paper.md

**Comment by yarikoptic** [comment]
with that note, just bringing attention to @kyleam @adswa @bpoldrack @jwodder @effigies  and @datalad/developers and @datalad/contributors .  Letter will go later today to invite more, but this could be the first wave to hopefully minimize future PR conflicts ;-)

**Comment by yarikoptic** [comment]
agreed and acted upon. I think this particular issue is resolved
