### ISSUE TITLE
Substantial scholarly effort: prior citations

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#5]
Google survey done on 20210319, stopped on page 6.

### "academic papers" by others:

-  Li, Q.; Xue, R. The Pipeline of Processing fMRI Data with Python Based on the Ecosystem NeuroDebian. Preprints 2019, 2019040027 (doi: https://doi.org/10.20944/preprints201904.0027.v2).
- Far, M. S., Stolz, M., Fischer, J. M., Eickhoff, S. B., & Dukart, J. (2021). JuTrack: A Digital Biomarker Platform for Remote Monitoring in Neuropsychiatric and Psychiatric Diseases. arXiv preprint arXiv:2101.10091.
https://arxiv.org/abs/2101.10091
- Langer, A., & Hai, D. V. N. Comparison of existing decen-tralized RDM solutions. https://vsr.informatik.tu-chemnitz.de/projects/2019/solidrdp/resources/ComparisonOfExingRdmSolutions.pdf
- Ioanas, H. I., Saab, B., & Rudin, M. (2017). Gentoo Linux for Neuroscience-a replicable, flexible, scalable, rolling-release environment that provides direct access to development software. Research Ideas and Outcomes, 3, e12095. https://doi.org/10.3897/rio.3.e12095
- Manera, A. L., Dadar, M., Fonov, V., & Collins, D. L. (2020). CerebrA, registration and manual label correction of Mindboggle-101 atlas for MNI-ICBM152 template. Scientific Data, 7(1), 1-9. https://doi.org/10.1038/s41597-020-0557-9
- Esteban, O., Ciric, R., Finc, K., Blair, R. W., Markiewicz, C. J., Moodie, C. A., ... & Gorgolewski, K. J. (2020). Analysis of task-based functional MRI data preprocessed with fMRIPrep. Nature protocols, 1-17. https://doi.org/10.1038/s41596-020-0327-3
- Esteban, O., Blair, R. W., Nielson, D. M., Varada, J. C., Marrett, S., Thomas, A. G., ... & Gorgolewski, K. J. (2019). Crowdsourced MRI quality metrics and expert quality annotations for training of humans and machines. Scientific data, 6(1), 1-7. https://doi.org/10.1038/s41597-019-0035-4
- Visconti di Oleggio Castello, M., Chauhan, V., Jiahui, G. et al. An fMRI dataset in response to “The Grand Budapest Hotel”, a socially-rich, naturalistic movie. Sci Data 7, 383 (2020). https://doi.org/10.1038/s41597-020-00735-4
- Arco, J. E., González-García, C., Díaz-Gutiérrez, P., Ramírez, J., & Ruz, M. (2018). Influence of activation pattern estimates and statistical significance tests in fMRI decoding analysis. Journal of neuroscience methods, 308, 248-260. https://doi.org/10.1016/j.jneumeth.2018.06.017
Teijeiro, T. (2020). Recommendations for the MIP Technical Development During HBP SGA3. https://infoscience.epfl.ch/record/276489
- Horien, C., Noble, S., Greene, A. S., Lee, K., Barron, D. S., Gao, S., … Scheinost, D. (2020). A hitchhiker’s guide to working with large, open-source neuroimaging datasets. Nature Human Behaviour. doi:https://dx.doi.org/10.1038/s41562-020-01005-4 
- Mak, M., Ren, L., Kong, L., & Wong, I. (2020). Validity of a physical activity tracker for heart rate measurement during aerobic exercise in people with Parkinson's disease. Parkinsonism & Related Disorders, 79, e42-e43. https://doi.org/10.1016/j.parkreldis.2020.06.172
- Keshavan, A., & Poline, J. B. (2019). From the wet lab to the web lab: a paradigm shift in brain imaging research. Frontiers in neuroinformatics, 13, 3. https://doi.org/10.3389/fninf.2019.00003
- Das, S., Lecours Boucher, X., Rogers, C., Makowski, C., Chouinard-Decorte, F., Oros Klein, K., ... & Evans, A. C. (2018). Integration of “omics” data and phenotypic data within a unified extensible multimodal framework. Frontiers in neuroinformatics, 12, 91. https://doi.org/10.3389/fninf.2018.00091
- Wiener, M., Sommer, F. T., Ives, Z. G., Poldrack, R. A., & Litt, B. (2016). Enabling an open data ecosystem for the neurosciences. Neuron, 92(3), 617-621. https://doi.org/10.1016/j.neuron.2016.10.037
- Rakhimov, O., & Umarov, F. (2020). Clinical assessment of ongoing constipation in patients with Parkinson's disease and solution with alternative approach. Parkinsonism & Related Disorders, 79, e41-e42. https://doi.org/10.1016/j.parkreldis.2020.06.169
- Huckins JF, daSilva AW, Wang R, Wang W, Hedlund EL, Murphy EI, Lopez RB, Rogers C, Holtzheimer PE, Kelley WM, Heatherton TF, Wagner DD, Haxby JV and Campbell AT (2019) Fusing Mobile Phone Sensing and Brain Imaging to Assess Depression in College Students. Front. Neurosci. 13:248. doi: https://doi.org/10.3389/fnins.2019.00248
- Wittkuhn, L., Schuck, N.W. Dynamics of fMRI patterns reflect sub-second activation sequences and reveal replay in human visual cortex. Nat Commun 12, 1795 (2021). https://doi.org/10.1038/s41467-021-21970-2 
 
### "academic papers" by us:

- DuPre, E., Hanke, M., & Poline, J. B. (2020). Nature abhors a paywall: How open science can realize the potential of naturalistic stimuli. Neuroimage, 216, 116330. https://doi.org/10.1016/j.neuroimage.2019.116330
- Yarkoni, T., Markiewicz, C. J., de la Vega, A., Gorgolewski, K. J., Salo, T., Halchenko, Y. O., ... & Blair, R. (2019). PyBIDS: Python tools for BIDS datasets. Journal of open source software, 4(40). https://dx.doi.org/10.21105%2Fjoss.01294
- Nastase, S. A., Halchenko, Y. O., Connolly, A. C., Gobbini, M. I., & Haxby, J. V. (2018). Neural responses to naturalistic clips of behaving animals in two different task contexts. Frontiers in neuroscience, 12, 316. https://doi.org/10.3389/fnins.2018.00316
- Hanke, M., Pestilli, F., Wagner, A. S., Markiewicz, C. J., Poline, J. B., & Halchenko, Y. O. (2021). In defense of decentralized research data management. Neuroforum, 1. https://doi.org/10.1515/nf-2020-0037
- Cheng, C. P., & Halchenko, Y. O. (2020). A new virtue of phantom MRI data: explaining variance in human participant data. F1000Research, 9. https://dx.doi.org/10.12688%2Ff1000research.24544.1
- Bannier, E., Barker, G., Borghesani, V., Broeckx, N., Clement, P., Emblem, K. E., ... & Zhu, H. (2021). The Open Brain Consent: Informing research participants and obtaining consent to share brain imaging data. https://doi.org/10.1002/hbm.25351
- Ghosh, S. S., Poline, J. B., Keator, D. B., Halchenko, Y. O., Thomas, A. G., Kessler, D. A., & Kennedy, D. N. (2017). A very simple, re-executable neuroimaging publication. F1000Research, 6. https://dx.doi.org/10.12688%2Ff1000research.10783.2
- Häusler, C. O. & Hanke, M.. (2021) A studyforrest extension, an annotation of spoken language in the German dubbed movie “Forrest Gump” and its audio-description. F1000Research, 10:54. https://doi.org/10.12688/f1000research.27621.1
- Wachtler, T., Bauer, P., Denker, M., Grün, S., Hanke, M., Klein, J., Oeltze-Jafra, S., Ritter, P., Rotter, S., Scherberger, H., Stein, A. & Witte, O.W. (2021). NFDI-Neuro: Building a community for neuroscience research data management in Germany. Neuroforum, 27(1). https://doi.org/10.1515/nf-2020-0036
- Dar, A. H., Wagner, A. S. & Hanke, M. (2020). REMoDNaV: Robust Eye-Movement Classification for Dynamic Stimulation. Behavior Research Methods. https://doi.org/10.3758/s13428-020-01428-x

**Comment by yarikoptic** [comment]
For those we decide to reference, to quickly get bibtex, here is my tiny helper

```shell
doiref () {
  # get bibtex record for a doi, copy to clipboard
  doi=$(echo $1 | sed -e 's,https*://.*doi\.org/,,g')
  curl --silent -L -d "" --header "Accept: application/x-bibtex; charset=utf-8" https://doi.org/$doi \
   | sed -e 's,%2F,/,g' | xsel -i
  xsel -o
}
```

**Comment by yarikoptic** [comment]
I guess now we are doomed to take this wonderful list from @mih and stick it somewhere on datalad.org . If only "RRIDs worked"  and we did not have to collate them manually ;)

**Comment by yarikoptic** [comment]
We have some references, overall development stats, and I do not think we need more "proof" of an effort.
But my weak soul can't "close" this non-issue ;)
