### ISSUE TITLE
complete and harmonize affiliations

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-paper-joss#51]
- [x] ~~may be we should/could just use the institution (like I did `Dartmouth College`) without specific departments/institutes within?  that would collapse many of McGill affiliations. (didn't check yet what JOSS requirement is)~~
- [ ] add town, state, United States for those which miss

**Comment by adswa** [comment]
Re your first point: When you only included a minimal affiliation in the multimatch paper, it didn't make it through review and I was asked to supply detailed information: (see https://github.com/openjournals/joss-reviews/issues/1525#issuecomment-508808886). However, I did not find a journal policy on that specifically.

**Comment by yarikoptic** [comment]
thank you @adswa .  then I guess let's keep them full and just harmonize (ensure that consistent across multiple entries for McGill, and overall)

**Comment by mih** [comment]
I pushed some FIXME affiliation annotations for people that have none right now
