### ISSUE TITLE
Reconsider "contributions" section

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#67]
ATM it states the license, where to find 3rd-party terms, and that there is a CONTRIBUTION file. The first two aspects are only vaguely related to "contributions", the latter is merely a reference.

Shouldn't we rather say:

- MIT license being "permissive" -- encourage unconstrained use and re-use in any context -- promote contribution rather than fork
- make explicit that anyone is welcome to contribute under these terms (no CLA or other bullshit)
- reference CONTRIBUTION as a source for *technical and procedural* information on how to contribute best

**Comment by yarikoptic** [comment]
Sounds good to me.
