### ISSUE TITLE
Paper structure/content

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#7]
The structure is mandated:

https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain

- A list of the authors of the software and their affiliations, using the correct format (see the example below).
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- A Statement of Need section that clearly illustrates the research purpose of the software.
- A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
- Acknowledgement of any financial support.

I think we should follow this (in particular the order, which is presently not the case).

I would also propose the following:

- make it very brief in general: mention things like datasets.d.o and extensions, but not details -- we should be able to reasonably be able to select to JOSS publication as a citation for a broad range of things, but we should not publish some half-baked intro now, that makes subsequent specialized publication more difficult
- exceptions to that (that I can see right now) would be aspects related to the development and adoption process, such as
    - extensive test, not just unittests in each PR
    - extensibility to be able to add features quickly, without having to pay much of a cost in -core, and also to not force independent contributors into a specific process and speed
    - how datalad is being used in existing projects by others (rather than speculating what it could be used for)

**Comment by yarikoptic** [comment]
I was thinking of an idea to wrap description into wikipedia like subsections making it into datalad autobiography: inception, early life, puberty, maturation, reception by public which could give reasoning for choices made etc

**Comment by mih** [comment]
> I was thinking of an idea to wrap description into wikipedia like subsections making it into datalad autobiography: inception, early life, puberty, maturation, reception by public which could give reasoning for choices made etc

This would not be compliant with the spirit of such manuscripts, at least as far as me familiarity with published manuscripts and the review process goes (https://joss.readthedocs.io/en/latest/review_checklist.html). I think this list here is key:

https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper

The JOSS paper (the compiled PDF associated with this submission) should only include:

- A list of the authors of the software and their affiliations.
- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- A clear statement of need that illustrates the purpose of the software.
- A description of how this software compares to other commonly-used packages in this research area.
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it.
- A list of key references including a link to the software archive.

**Comment by yarikoptic** [comment]
yes, there are required components (you listed) and it must not be a "full length paper".  But usually there is extra section and often (e.g. randomly 2nd hit on current list: https://joss.theoj.org/papers/10.21105/joss.03049) presentation of "how and why" any particular feature was developed. That is why I thought that chronological presentation of developments would even well fit within "A Statement of need" section after some statement of need summary: after all "the need" datalad is addressing also changed through time, and all the extensions/testing/etc was introduced not for fun but to address a need. "Mentions" is really that "Reception by public".  Anyways -- just an idea ;)

**Comment by yarikoptic** [comment]
I think structure is there call to co-authors is about to be out, so I think this could be closed
