### ISSUE TITLE
Complete acknowledgements

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#8]
Before this issue can be closed, all eventual authors must have signed off here.

- #57 
- TVB-Cloud
- HBP
- ...

I would prefer to structure the acknowledgements with the following order:

1. Thx to people of particular importance (possibly indicating their role)
2. All contributors (list)
3. Grant numbers (list)

**Comment by yarikoptic** [comment]
For `1. Thx to people of particular importance` I think only of Jim.  I do not think we should re-list co-authors here.  Anyone we are missing?

Re grants - I think it is valuable to keep CRCNS (NSF+BMBF) grants separate as without them DataLad would not happen, and then  follow with all the others. Pretty much what we have already

Re all contributors - decision was made and nodded-approved to have it on opt-in with a very liberal cut off of 3 contributions, we have that.
I will merge #69 and reorder (moving Jim to ppl) for consistency of grants, people. So let's go 3, 1, 2 with aforementioned aspects in mind.

**Comment by yarikoptic** [comment]
or actually, indeed let's put ppl first!
