### ISSUE TITLE
Add or purge metadata?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-paper-joss#85]
I still think that we should bring 4th point which would touch on metadata support in DataLad:
- we do have it, even if it has being reworked
  - we do point to other extensions, and I think it would only be beneficial to point to datalad-metalad as "the future"
- it would add value for "DataLad" as addition to git/git-annex
  - flexible metadata extraction and aggregation is a very unique feature
  - it could interest some metadata-savvy folks struggling with their data/metadata archives
- we did get questions/queries about metadata on issues and neurostars, so some users are at least interested in it or do use it
- Figure 1 mentions it ("and metadata", "metadata aggregation") -- if decide to not bother, we should purge from the figure

WDYT?

**Comment by bpoldrack** [comment]
I think it would be better to explicitly point to metalad as "the future" than leaving it out. At least whoever reads it would be pointed to the right thing rather than find "old" references elsewhere.

**Comment by mih** [comment]
I don't mind adding it (moving up the existing pointer to `datalad-metalad`). It should be briefer than the others, and have a clear notion of "in progress" IMHO. I will try to propose a snippet later today.
