### ISSUE TITLE
Stats on datasets.d.o

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#86]
> A testament of this is datasets.datalad.org, created as the project’s initial goal to provide a data distribution with unified access to already available public data archives in neuroscience, such as crcns.org and openfmri.org. It is curated by the DataLad team, and provides, at the time of publication, streamlined access to over 250 TBs of data across a wide range of projects
and archives in a fully modularized way.

The paper has the above, which is critical and the key evidence that the beast works. However, rather than "250TB" (where we claim that git-annex handles any size already on its own), we should add the number of datasets, and number of dataset sources/portals as indicators of how much versatility is captured by DataLad (not just git-annex) in this single collection.

**Comment by yarikoptic** [comment]
ok, will get number of datasets (if we wait for a week it would grow by a few thousands -- I will push one dataset per shub:// repo, since why not).  Not sure how to figure out an exact number of "sources/portals" - any ideas?

**Comment by mih** [comment]
I don't think it needs a precise count, but it surely is thousands, and maybe a dozen portals/labs that provide?
