### ISSUE TITLE
Fix date in YODA reference

### ISSUE THREAD

**Issue by mih** [datalad/datalad-paper-joss#87]
2011 cannot be.

**Comment by bpoldrack** [comment]
2018 according to https://f1000research.com/posters/7-1965

**Comment by bpoldrack** [comment]
We currently link https://github.com/myyoda/myyoda which was created only this year. A bit strange to then give the year the poster was published. I don't know - what do we link?

**Comment by yarikoptic** [comment]
Thanks for spotting.  Indeed 2021 not 2011 was intended ;) pushed the fix
