### ISSUE TITLE
Migrate into the datalad repository once the paper is ready

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-paper-joss#91]
In order to submit to JOSS:

> Your paper (paper.md and BibTeX files, plus any figures) must be hosted in a Git-based repository together with your software (although they may be in a short-lived branch which is never merged with the default).

**Comment by yarikoptic** [comment]
Thank you @adswa. I think it is better to keep it in a separate detached branch, e.g. `joss-paper` so clone of codebase doesn't necessarily need to fetch the objects for the paper (unless all branches are cloned as by default - no way around that). ATM it is not too big at least (2MB of .git/objects after repacking)

**Comment by yarikoptic** [comment]
I do not think we even need to migrate per se.  Just did
```
$> git remote add datalad http://github.com/datalad/datalad

$> git push datalad master:paper-joss    
Enumerating objects: 852, done.
Counting objects: 100% (852/852), done.
Delta compression using up to 12 threads
Compressing objects: 100% (404/404), done.
Writing objects: 100% (852/852), 1.25 MiB | 60.78 MiB/s, done.
Total 852 (delta 480), reused 786 (delta 437), pack-reused 0
remote: Resolving deltas: 100% (480/480), done.
remote: 
remote: Create a pull request for 'paper-joss' on GitHub by visiting:
remote:      https://github.com/datalad/datalad/pull/new/paper-joss
remote: 
To github.com:datalad/datalad
 * [new branch]      master -> paper-joss

$> git describe --always
45676dc
```
and there we have it now: https://github.com/datalad/datalad/tree/paper-joss .  So we could even keep using this repo for staging/reviewing and then push there once "satisfied"

**Comment by yarikoptic** [comment]
submitted, let's see if/how I screwed up, but we can consider this issue addressed
